service: keys

permissions:
  - key: 'key.write'
    description: 'Create or delete api keys'
    scopes:
      - 'user'
  - key: 'service.write'
    description: 'Create/delete services'
    scopes:
      - 'user'
  - key: 'service.read'
    description: 'Read services'
    scopes:
      - 'user'
